### ISSUE TITLE
Feature Request: Add Dark Mode

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7-test-panel#109]
It'd be pretty neat if the Test Panel had a dark mode. 

It's a stark contrast having your entire system use dark mode then see the bright light of the test panel before going to a dark mode Specify Instance. 

Here is a mock up of how this might look.
<img width="1791" alt="Screenshot 2024-01-03 at 1 59 53 PM" src="https://github.com/specify/specify7-test-panel/assets/53784701/38352fe1-7533-4997-acd1-cd0b9870ee9f">

**Comment by maxpatiiuk** [comment]
You can get dark mode already for all websites by enabling it in chrome:

1. Go to chrome://flags/
2. Search for "Auto Dark Mode for Web Contents" flag
3. Set it to "Enable with selective inversion of everything"
4. Restart Chrome, and enjoy:

![Screenshot 2024-01-03 at 12 48 16](https://github.com/specify/specify7-test-panel/assets/40512816/0ddb4556-ff94-434e-9551-adefc247b6bd)

**Comment by carlosmbe** [comment]
Me and my eyes wanted to take a moment to express our appreciation.
