### ISSUE TITLE
`edge` deploys `latest` instances

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7-test-panel#112]
https://github.com/specify/specify7-test-panel/assets/37256050/83bb20a8-a34a-4521-b11f-f7615fa76a0c

Can't test production until this is fixed.

**Comment by maxpatiiuk** [comment]
Cause:
when adding new deployment, we sort tags by most recently modified, and pick the most recent as the branch for the new deployment
when pushing to a branch, that branch name and "latest" are the two most recent
"latest" should have been excluded from this but it wasn't
instead, "latest" was only excluded from the list of options the user saw, not the list of options the program considered
if program selects "latest", but such option is not available in the list, the list will show the first option "edge", even though "edge" isn't selected. workaround is to manually pick any other option and then pick "edge" again

the bug in question has been there for more than a year.
the fact that it only started to happen now suggested that the ordering of tags coming from dockerhub changed

**Comment by maxpatiiuk** [comment]
Fixed in 1618414

**Comment by maxpatiiuk** [comment]
Resolved for all new deployments going forward - existing "latest" deployments can be removed and added back to fix the issue.
Could you please verify the fix and close this issue once confirmed?

**Comment by grantfitzsimmons** [comment]
Yes, thank you so much @maxpatiiuk !

**Comment by grantfitzsimmons** [comment]
Appears to fix the issue!
