### ISSUE TITLE
Readiness indicator inaccurate

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7-test-panel#17]
![testpanelreadinessinaccurate](https://user-images.githubusercontent.com/37256050/144275276-d5138284-2fb9-49d9-ab80-17e99ee92df2.gif)
The readiness indicator is inaccurate after changing an instance's version of Specify to edge and saving. It immediately reads Ready and does not function.

**Comment by maxxxxxdlp** [comment]
The indicator updates once every 10 seconds

**Comment by maxxxxxdlp** [comment]
Probably was caused by https://github.com/specify/specify7-test-panel/issues/35
