### ISSUE TITLE
Creating CSV & KML from query results fails

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7-test-panel#2]
When I run a query and click on either 'Create CSV' or 'Create KML' I get the usual notification that the query export to CSV has completed but my browser says that the download failed and there is no file. I tried it on chrome and Microsoft edge and on different databases using the docker build and default values build
![Screenshot (155)](https://user-images.githubusercontent.com/28809154/102252845-34803500-3ecc-11eb-9bae-876c34bc4e1d.png)

**Comment by benanhalt** [comment]
Fixed in 3dde2c8c76d7a709cdfb0c5c6b718c1394ea40bb
