### ISSUE TITLE
SpAuditLog is full error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7-test-panel#28]
`{"error":"Error: Command failed: mysql -uroot -proot -hmariadb --database \"shellmuseum\" < /tmp/upload_8eacb254c3dcf5aa51dc9cad29663246\nERROR 1114 (HY000) at line 8935: The table 'spauditlog' is full\n"}`

After attempting to upload [this database](https://drive.google.com/open?id=1EbQyIN6VCdkq3IfIewi4FtKOrD9IsIY1&authuser=grant%40specifysoftware.org&usp=drive_fs).

**Comment by maxxxxxdlp** [comment]
The server is out of storage. Try to delete some databases if you can

**Comment by maxxxxxdlp** [comment]
I have just deleted 12gb of old files on that server. That should fix the issue.
Still, it's a good idea to regularly delete unused databases

**Comment by grantfitzsimmons** [comment]
`Error: Error: Table '***.spversion' doesn't exist`

I'll clear out databases regularly that I won't be using again anytime soon!
