### ISSUE TITLE
Ability to delete deployments

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7-test-panel#32]
It would be nice to be able to delete instances from the test panel using a GUI. Maybe just a trash can icon to the right of each instance.

**Comment by grantfitzsimmons** [comment]
Retaining unnecessary deployments crowds the URLs and can confuse navigation. I understand how the server structures URL prefixes (edge-2 or edge-2-2) and I can navigate intuitively knowing what order each deployment was setup in. 

It is not necessary to implement, just something that would help with organization

**Comment by maxxxxxdlp** [comment]
Ah, that's a separate issue. I though it would continue numbering the prefixes (e.i. `edge-3`)
Opened https://github.com/specify/specify7-test-panel/issues/33
